FROM 192.168.1.77:5001/ibmcom/ace-server:11.0.0.12-r1-20210422-114930-amd64
COPY Customer /home/aceuser/Customer
RUN export LICENSE="accept" \
    && source /opt/ibm/ace-11/server/bin/mqsiprofile \
    && mkdir /home/aceuser/bars \
    && mqsipackagebar -a bars/FE.bar -k Customer \
    && mqsibar -a bars/FE.bar -w /home/aceuser/ace-server \
    && chmod -R 777 /home/aceuser/ace-server/run/Customer
