apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ace-pipeline-run-sink
spec:
  pipelineRef:
    name: acecicd-pipeline-sink
  resources:
    - name: git-repo
      resourceRef:
        name: acecicd-res-git
    - name: image
      resourceRef:
        name: acecicd-res-image
